language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - echo "deb http://de.archive.ubuntu.com/ubuntu trusty universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install libmimetic-dev
script:
  - mkdir build && cd build
  - cmake ..
  - make
